/*
Tasks:
1. Calculate the overall revenue.
2. Determine revenue generated by each branch.
3. Compute the overall gross profit.
4. Assess gross profit by branch.

Purpose:
- Gain insights into total and branch-specific revenue to inform strategic decisions.
- Evaluate gross profit to understand the profitability of sales after accounting for production costs.
- Use these insights to optimise pricing, inventory, and branch performance.
*/

--Total Revenue
SELECT 
    ROUND(SUM(total_taxincluded), 2) 
FROM 
    supermarket_sales_staging;

--Revenue by Branch
SELECT 
    branch,
    ROUND(SUM(total_taxincluded), 2) 
FROM 
    supermarket_sales_staging
GROUP BY 
    branch;


--Total Gross Profit
SELECT 
    ROUND(SUM(total_taxincluded - cogs), 2) 
FROM 
    supermarket_sales_staging;


--Gross Profit by Branch
SELECT 
    branch,
    ROUND(SUM(total_taxincluded - cogs), 2) 
FROM 
    supermarket_sales_staging
GROUP BY
    branch;


/*
Here's the breakdown:

Branch C has the highest revenue and gross profit among the three branches.

Given the similar revenue values (around $106,200 to $110,569), the spread of revenue is likely small. Branch C has the highest revenue, while Branches A and B have nearly identical revenues. This suggests a fairly uniform distribution of revenue with a slight outlier (Branch C)

All branches have a gross profit margin of approximately 4.76%.

The overall supermarket also maintains a consistent gross profit margin of 4.76%.

*/

--
The first query gives a snapshot of the overall financial health by calculating the total revenue.
The second query breaks down this revenue by each branch to identify top-performing and underperforming branches.
The third query calculates the total gross profit, providing an understanding of the profitability after accounting for production costs.
The fourth query offers a branch-wise breakdown of gross profit, helping to pinpoint which branches are most profitable.